# Generated by Django 3.0.5 on 2020-05-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('city_link', models.CharField(max_length=300)),
                ('climate', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
