# Generated by Django 3.0.5 on 2020-05-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_link',
            field=models.CharField(default='/', max_length=300),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(default='kathmandu', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='climate',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(default='unable to parse', max_length=100),
        ),
    ]
